### ISSUE TITLE
연습문제 1.

### ISSUE THREAD

**Issue by devms0201** [ksw626/python_work#1]
구구단을 1단 ~9단 까지 출력하는 프로그램을 작성해보자

입력 : non
출력 
-------1DAN--------
1 * 1 = 1
1 * 2 = 2 
    .
    .
    .
1 * 8 = 8
1 * 9 = 9 
-------2DAN--------
2 * 1 = 2 
2 * 2 = 4 
  .
  .
  .

**Comment by ksw626** [comment]
https://github.com/ksw626/python_work/blob/master/ex1.py

**Comment by devms0201** [comment]
good
