### ISSUE TITLE
연습문제 1.1

### ISSUE THREAD

**Issue by devms0201** [ksw626/python_work#3]
구구단을 1단 ~9단 중 홀수단만 출력하는 프로그램을 작성해보자
========================================
입력 : non
출력
-------1DAN--------
1 * 1 = 1
1 * 2 = 2
.
.
.
1 * 8 = 8
1 * 9 = 9
-------2DAN--------
SKIP
-------3DAN--------
3 * 1 = 3 
3 * 2 = 6 
  .
  .
  .
3 * 8 = 24
3 * 9 = 27 
-------4DAN-------
SKIP
-------5DAN-------
5 * 1 = 5 
5 * 2 = 10 
  .
  .
  .

**Comment by ksw626** [comment]
https://github.com/ksw626/python_work/blob/master/ex1_1.py

**Comment by devms0201** [comment]
good 
반복문에서 break와 continue의 차이에 대해서 정리해보자
