### ISSUE TITLE
연습문제 1.2

### ISSUE THREAD

**Issue by devms0201** [ksw626/python_work#4]
사용자의 입력을 받아서 해당 단을 출력핟도록하자 

입력 : input gugudan
9
출력 : 
-----9DAN-----
9 * 1 = 9 
.
.
.

**Comment by ksw626** [comment]
https://github.com/ksw626/python_work/blob/master/ex1_2.py

**Comment by ksw626** [comment]
https://github.com/ksw626/python_work/blob/master/ex1_2.py

**Comment by ksw626** [comment]
https://github.com/ksw626/python_work/blob/master/ex1_2.py
