### ISSUE TITLE
연습문제 2

### ISSUE THREAD

**Issue by devms0201** [ksw626/python_work#5]
별 피라미드를 만들어보자 
======================
입력 : none
출력 : 
-----pryamid-----
*
**
***
****
*****
-----end-----

**Comment by ksw626** [comment]
https://github.com/ksw626/python_work/blob/master/ex2.py

**Comment by devms0201** [comment]
잘 만들었는데 
다른 방법으로도 마들어보면 좋을거같다. 
원래 결과가 나오느 방법은 여러개가있으니까 ㅋ
다른버전으로도 만들어봐

**Comment by ksw626** [comment]
https://github.com/ksw626/python_work/blob/master/ex2(1).py
