### ISSUE TITLE
연습문제3-1

### ISSUE THREAD

**Issue by devms0201** [ksw626/python_work#8]
숫자 1234567890056798776556543211234876590 를 가지고 있는 데이터가 있다. 
유저가 숫자 하나를 입력하면 해당 숫자가 데이터에 몇개가 있는지 알려주도록하자. 
-----------------------------------------
입력 : 1
출력 : 3
입력 : 5
출력: 6
-----------------------------------------
+ 유저가 두자리 이상의 숫자를 입력하면 어떻게하면 좋을까? 생각해보자

**Comment by ksw626** [comment]
https://github.com/ksw626/python_work/blob/master/ex3_1.py

이건좀 어렵네 리스트말고 다른방법으로 할수가없나

**Comment by devms0201** [comment]
문제가 제시하는 입력은 2개인데 너의 프로그램은 입력을 한번뿐이 못하는구나....

**Comment by ksw626** [comment]
일단 저기서 원하는 값으로는 나오게 만들어놨는데 문자열이나 2자리수 이상일때 다른 출력을 하고싶은데 
그건 이것저것 충돌해서 어렵네
https://github.com/ksw626/python_work/blob/master/ex3_1_1.py

**Comment by ksw626** [comment]
오 돌아간다 ㅋㅋㅋㅋ
https://github.com/ksw626/python_work/blob/master/ex3_1_2.py
삽질했던 것들도 정리해야되는데

**Comment by devms0201** [comment]
올 ㅋㅋㅋㅋㅋ  잘했다 ㅋㅋㅋㅋㅋ 
굳굳
